Add dependencies to rosidl in CMakeLists.txt (#349)
I followed this tutorial and without adding dependencies to rosidl, the error message:
ImportError: /home/dan/work/microros_ws/install/hw_msgs/lib/libhw_msgs__rosidl_generator_c.so: undefined symbol: std_msgs__msg__Header__fini
pops up(in my case because of std_msgs) when publishing with the agent. I had no other errors in the compilation process.

In the official tutorial it's also present:
https://docs.ros.org/en/foxy/Tutorials/Single-Package-Define-And-Use-Interface.html